### ISSUE TITLE
TODO: ISO code generator

### ISSUE THREAD

**Issue by mengping** [mengping/country_iso#1]
- [ ] add more variations of country names
- [ ] test with existing files
- [ ] produce matching results
- [ ] give notification of error if name match could not be found and prompt to add to country_name.csv file
